CREATE DATABASE customer_behavior;
use customer_behavior;
SELECT * FROM customer LIMIT 5;

-- Q1) what is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount)as revenue
from customer
group by gender

-- Q2) which customer used discount but still spend more than average amount?

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes'
and purchase_amount >= (
    select AVG(purchase_amount)
    from customer
);

-- 	Q3) which are the top 5 product with highest avg rating?

select item_purchased,
ROUND(AVG(review_rating), 2) as "Average Product Rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5;

-- Q4) compare avg purchase amount b/w standard and express shaipping 
select shipping_type,
AVG(purchase_amount)
from customer
where shipping_type in ('standard','Express')
group by shipping_type

-- Q5)  do subscibed customer spend more..? compare avg spend and total revenue b/w sub and non sub

select subscription_status,
count(customer_id) as total_customers,
avg(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue desc, avg_spend desc;

-- Q6) which 5 product have the highest percentage of purcheze with discount applied?
 select item_purchased,
ROUND(
    sum(case when discount_applied = 'Yes' then 1 else 0 end)
    * 100.0 / count(*),
2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7) segment customer into new, returning and loyal

with customer_type as (
    select customer_id,
    previous_purchases,
    case
        when previous_purchases <= 1 then 'New'
        when previous_purchases between 2 and 10 then 'Returning'
        else 'Loyal'
    end as customer_segment
    from customer
)

select customer_segment,
count(*) as number_of_customers
from customer_type
group by customer_segment;


